# Generated by Django 2.1.5 on 2019-01-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newsupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdate',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='newsupdate',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
