# Generated by Django 2.1.5 on 2019-01-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190129_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeupdate',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
