# Generated by Django 2.1.5 on 2019-01-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_noticeupdate_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeupdate',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
